/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clases.usuariodb.UI;

import com.clases.usuariodb.DAO.PreguntaDAO;
import com.clases.usuariodb.modelos.Pregunta;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author magb
 */
public class framePreguntas extends javax.swing.JInternalFrame {
    List<Pregunta> lista = new ArrayList<>();
    private  List<JButton> botones;
    private int indice;
    private int contador;
    
         //Contador peguntas
                int botonRespuesta=0;
                int aciertos=0;
                int errores=0;
    
    /**
     * Creates new form Preg
     */

    public framePreguntas() {
 
              initComponents();
              botones = new ArrayList<>();
              indice=0;
              
              contador=0;
              
           
        
              //Pregunta p1 = new Pregunta (1,"Descripcionm 1??","ruta",true,true,true);
                                        //numero, descripcion,ruta_imagen,resultados  
              //Pregunta p2 = new Pregunta (2,"Descripcionm 2??","c:/imgs/ui.png",true,true,true);
              //lista.add(p1);
              //lista.add(p2);
              PreguntaDAO preguntaDao = new PreguntaDAO();
              lista=preguntaDao.listar();
                      
              
              jTextField1.setText(lista.get(contador).getPregunta() );

              jTextArea1.setText("hola\nhola depues");
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelIzquierdo = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        main.setLayout(new java.awt.BorderLayout());

        panelPrincipal.setToolTipText("");
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pregunta");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 30));

        jTextField1.setText("jTextField1");
        panelPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 280, 50));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 90, 50));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 110, 40));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 170, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 400, 110));

        jLabel1.setText("jLabel1");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 115, 60));

        main.add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelInferior.add(jButton2);

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelInferior.add(jButton3);

        main.add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelIzquierdo.setLayout(new javax.swing.BoxLayout(panelIzquierdo, javax.swing.BoxLayout.Y_AXIS));

        jButton7.setText("Terminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelIzquierdo.add(jButton7);

        jButton1.setText("Genera B");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelIzquierdo.add(jButton1);

        main.add(panelIzquierdo, java.awt.BorderLayout.LINE_START);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JButton boton = new JButton ("Botn"+indice);
        panelPrincipal.add(boton);
        botones.add(boton);
        indice ++;
      
   
                
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        contador--;
       jTextField1.setText(lista.get(contador).getPregunta() );
       jLabel1.setIcon(new ImageIcon(lista.get(contador).getRuta()));
       //jLabel1.setIcon(new ImageIcon("c:/imgs/ui.png"));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        contador++;
         jTextField1.setText(lista.get(contador).getPregunta() );
         String a = lista.get(contador).getRuta();
         jLabel1.setIcon(new ImageIcon(a));
        
         if (botonRespuesta==lista.get(contador).getRespuesta()){
             aciertos++;
         }else{
                 errores++;
         }
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        botonRespuesta=3;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         botonRespuesta=2;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         botonRespuesta=1;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.out.println(errores);
        System.out.println(aciertos);
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
